# Generated by Django 5.0.4 on 2024-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_remove_slot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.CharField(choices=[('9:30-10:30', '9:30-10:30'), ('10:30-11:30', '10:30-11:30'), ('11:30-12:30', '11:30-12:30'), ('12:30-1:30', '12:30-1:30'), ('1:30-2:30', '1:30-2:30'), ('2:30-3:30', '2:30-3:30'), ('3:30-4:30', '3:30-4:30'), ('4:30-5:30', '4:30-5:30'), ('5:30-6:30', '5:30-6:30'), ('6:30-7:30', '6:30-7:30')]),
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
