# Generated by Django 5.0.4 on 2024-05-05 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_book_time_delete_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
